# Fetching the latest node image on apline linux
FROM node:14-alpine

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install

# Copying all the files in our project
COPY . .
COPY .env.docker .env

# Building our application
CMD ["npm", "run", "start"]