version: '3'

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"

  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    expose:
      - "27017"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting of `node_modules`
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file: 
      - .env.docker
      - .env.docker.local      
    command: yarn run start:dev
    depends_on:
      - redis
      - mongodb

  nodejs_worker:
    build: .
    command: node dist/crawler.main.js
    depends_on:
      - redis
      - mongodb

  python_worker:
    build: ./workers
    depends_on:
      - redis
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3030:80"
    depends_on:
      - web

  widget:
    build:
      context: ./widget
    ports:
      - "3031:80"
    depends_on:
      - web

volumes:
  db-data:
