###################
# DEVELOPMENT
###################

FROM node:20-alpine As development

WORKDIR /usr/src/app

COPY package*.json yarn.lock ./

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

RUN yarn install

COPY . .

ENV NODE_ENV development

EXPOSE 3000

CMD ["yarn", "run", "start:dev"]
