# Fetching the latest node image on apline linux
FROM node:14-alpine

# Declaring env
ARG BASE_TARGET _parent

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install

# Copying all the files in our project
COPY . .

# Building our application
CMD [ "npm", "run", "start" ]